{{- if .Values.secrets.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-secrets
  namespace: {{ .Values.app.name }}
  labels:
    {{- include "app-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Values.secrets.secretStore.name }}
    kind: SecretStore
  target:
    name: database-secrets
    creationPolicy: Owner
  data:
  {{- range .Values.secrets.database.keys }}
  - secretKey: {{ . }}
    remoteRef:
      key: {{ $.Values.secrets.database.secretName }}
      property: {{ . }}
  {{- end }}

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: application-secrets
  namespace: {{ .Values.app.name }}
  labels:
    {{- include "app-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Values.secrets.secretStore.name }}
    kind: SecretStore
  target:
    name: application-secrets
    creationPolicy: Owner
  data:
  {{- range .Values.secrets.application.keys }}
  - secretKey: {{ . }}
    remoteRef:
      key: {{ $.Values.secrets.application.secretName }}
      property: {{ . }}
  {{- end }}
{{- end }}